//
// Created by jaylesr on 24/06/16.
//

#ifndef PREY_CONFIG_H
#define PREY_CONFIG_H


#define GYROSCOPE_UPDATE_FREQUENCY_MS 2000
#define ACCELEROMETER_UPDATE_FREQUENCY_MS 100
#define GPS_UPDATE_FREQUENCY_MS 100

#define ORIENTATION_MANAGER_UPDATE_FREQUENCY_MS 1000

#endif //PREY_CONFIG_H
