//
// Created by jaylesr on 24/06/16.
//

#ifndef PREY_CONFIG_H
#define PREY_CONFIG_H

#define SAVE_ACCELEROMETER_FILENAME "Accelerometer_saving"
#define SAVE_GYROSCOPE_FILENAME "gyroscope_saving"

#define MAX_FILENAME_SIZE 512
#define MAX_LOG_MESSAGE_SIZE 512

#define GYROSCOPE_UPDATE_FREQUENCY_MS 2000
#define ACCELEROMETER_UPDATE_FREQUENCY_MS 3000
#define GPS_UPDATE_FREQUENCY_MS 100

#define ORIENTATION_MANAGER_UPDATE_FREQUENCY_MS 1000

#endif //PREY_CONFIG_H
